project_id = "ueczlkbzrkzomcyeguaq"

[auth]
minimum_password_length = 12
# Require strong passwords with upper, lower, digits, and symbols.
password_requirements = "lower_upper_letters_digits_symbols"
